### ISSUE TITLE
Error in training on own data

### ISSUE THREAD

**Issue by divsidhu-26** [kahst/BirdCLEF2017#5]
I got the following error on trying to train with my own data. I followed the instructions in README.md .
Can you explain what is happening?

Traceback (most recent call last):
  File "birdCLEF_train.py", line 791, in <module>
    loss = train_net(image_batch, target_batch, lr)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError: 
Apply node that caused the error: Elemwise{sqr,no_inplace}(Elemwise{Sub}[(0, 0)].0)
Toposort index: 156
Inputs types: [TensorType(float64, 4D)]
Inputs shapes: [(128, 128, 64, 128)]
Inputs strides: [(8388608, 65536, 1024, 8)]
Inputs values: ['not shown']
Outputs clients: [[Sum{axis=[0, 2, 3], acc_dtype=float64}(Elemwise{sqr,no_inplace}.0)]]

**Comment by kahst** [comment]
This is a memory error, typically raised when the GPU runs out of memory. There are basically two things you can do: Reduce the Batch Size or reduce the net complexity (less filters). You can also reduce the image resolution, but that requires more adjustments and might not be as applicable as the other two strategies.

**Comment by PubuduLakshan** [comment]
I'm young researcher from srilanka. I got the following error on trying to train with my own data. I followed the instructions in README.md .

ERROR (theano.gof.opt): Optimization failure due to: local_abstractconv_check
ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(2, 2), filter_flip=True, imshp=(None, 1, 256, 512), kshp=(64, 1, 7, 7), filter_dilation=(1, 1), num_groups=1, unshared=False}(input, W)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):


theano.gof.opt.LocalMetaOptimizerSkipAssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against? On the CPU we do not support float16.

Can you explain this issue.
project built in windows 10 64 bit on the CPU
